//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellphoneComponent
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoTonKho
    {
        public string MaBaoCao { get; set; }
        public Nullable<int> Thang { get; set; }
        public Nullable<int> Nam { get; set; }
        public string MaHangHoa { get; set; }
        public Nullable<int> SoLuongTonDau { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
        public Nullable<int> SoLuongXuat { get; set; }
        public Nullable<int> SoLuongTonCuoi { get; set; }
    
        public virtual HangHoa HangHoa { get; set; }
    }
}
