//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CellphoneComponent
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDatHang
    {
        public string MaPhieuDatHang { get; set; }
        public Nullable<System.DateTime> NgayDat { get; set; }
        public string MaNhanVien { get; set; }
        public string MaNhaCungCap { get; set; }
        public Nullable<decimal> TongTien { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayChinhSua { get; set; }
    
        public virtual ChiTietPhieuDatHang ChiTietPhieuDatHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
